### PR TITLE
Refresh: Alpine base image

### PR DESCRIPTION
**Pull request by mor1**
Per discussion with @avsm, this PR attempts to refresh this repo by deleting everything and then replaying commits from `mor1/arm-image-builder`.

While the refresh is not complete (manual interventions are still required), it is largely scripted and should work to build Cubieboard2/Cubietruck images containing Xen with an Alpine 3.4.0 dom0 and then Alpine and Debian domUs.

For the record the process followed was approximately:

```
git clone git@github.com:mor1/xen-arm-builder.git
cd xen-arm-builder/
git co -b alpine-base-image
git reset --hard 2296f3d
git rm -r *
git commit -m "nuke everything"
git remote add mor1-arm-image-builder ~/research/projects/ucn/src/arm-image-builder
git fetch mor1-arm-image-builder
git merge --allow-unrelated-histories mor1-arm-image-builder/master
git push origin alpine-base-image
```

If there's a better way, say so and I'll recreate this PR :)

### CODE REVIEW

**Comment by talex5** [comment]
If I'm understanding what you want to do correctly, you could use

    git merge -s ours origin/master

where the current branch is the one you want to keep and `origin/master` is the branch whose history you want to keep but whose files you don't want in the merged version.

**Comment by avsm** [comment]
I have tagged v1.0 with the old image changeset, so that we have it on record.

**Comment by mor1** [comment]
@talex5 That doesn't seem to work for the same reason that I had to `--allow-unrelated-histories` in the approach I took (which would end up at the same place as your suggestion wouldn't it?).

I redid this PR by rebuilding the branch, with a few bug fix commits; the new merge seems to have worked as no conflicts showing above:
```
git clone git@github.com:mor1/xen-arm-builder.git
git remote add -f mor1-arm-image-builder ~/research/projects/ucn/src/arm-image-builder
cd xen-arm-builder
git remote add -f arm-image-builder ~/research/projects/ucn/src/arm-image-builder
git rm -fr .
git commit -m "nuke everything"
git merge --allow-unrelated-histories arm-image-builder/master
git co alpine-base-image
git merge master
git push
```

**Comment by avsm** [comment]
```
+ cd linux
+ git checkout -f v4.4.14
error: pathspec 'v4.4.14' did not match any file(s) known to git.
```

**Comment by mor1** [comment]
@avsm based on the `+ cd linux` above the error, that was fixed when I fixed the path to match the clone of the stable repo, `cd linux-stable` rather than `cd linux`.

(https://github.com/mor1/arm-image-builder/commit/c20f6e2d16d3e88349964644c525ecca8ee5c727)

**Pull request merged**
